<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-02-08 22:57:12
 * @@Modify Date: 2019-12-02 15:21:53
 * @@Function:
 */

$menu = $this->_sysCfg->topmenu;
$vmenu = $this->_sysCfg->vmenu;

if( !$menu['enabled'] && !$vmenu['enabled'] ){
	echo $this->getChildHtml();
	return;
}

// drawMainMenu vs DrowMobileMenu
$homeHtml  	= $this->drawHomeMenu();
$menuHtml  	= $this->drawMainMenu();
$extraHtml 	= $this->drawExtraMenu();
$mobileMenu = $menuHtml['mobile'];
$drawHomeMenu  = $menu['home'] ? $homeHtml : '';
$drawMainMenu  = '';
$drawExtraMenu = $menu['extraCat'] ? $extraHtml : '';
?>
<nav class="navigation mean-nav navigation-mobile" role="navigation" data-action="navigation" <?php echo $menu['exclude_html_desktop'] ? 'data-exclude_html_desktop="1"' : '' ?> >
	<ul class="nav-mobile" data-alo-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
		<?php echo $mobileMenu ?>
		<?php echo $drawExtraMenu ?>
	</ul>
</nav>
<?php if($vmenu['enabled']) : ?>
	<?php
		$vdrawHomeMenu  = $vmenu['home'] ? $homeHtml : '';
		$vdrawMainMenu  = '';
		$vdrawExtraMenu = $vmenu['extraCat'] ? $extraHtml : '';
		if($vmenu['mainCat']){
			$vdesktop 	= $menuHtml['desktop'];
			$vids  = explode(',', $vmenu['notIncludeNav']);
			foreach ($vids as $id) { unset($vdesktop[$id]); }
			$vdrawMainMenu = implode("\n", $vdesktop);
		}
	?>
	<div class="vmagicmenu vertical-menu clearfix" <?php echo $vmenu['exclude_html_mobile'] ? 'data-exclude_html_mobile="1"' : '' ?> >
		<div class="block-title block-title-vmagicmenu v-title">
	        <strong>
	        	<span class="vmagicmenu-subtitle"><?php echo __($this->getRootName())?></span>
	            <span class="icon-menu">
	                <span></span>
	                <span></span>
	                <span></span>
	            </span>
	        </strong>
	    </div>
		<div class="block-vmagicmenu-content">
			<ul class="nav-desktop vmagicmenu-narrow clearfix">
				<?php echo $vdrawHomeMenu ?>
				<?php echo $vdrawMainMenu ?>
				<?php echo $vdrawExtraMenu ?>
				<li class="all-cat"><span><?php echo __('All Categories')?></span><span style="display:none"><?php echo __('Close')?></span></li>
			</ul>
		</div>
	</div>
<?php endif ?>
<?php if($menu['enabled']) : ?>
	<?php
		if($menu['mainCat']){
			$desktop 	= $menuHtml['desktop'];
			$ids  = explode(',', $menu['notIncludeNav']);
			foreach ($ids as $id) { unset($desktop[$id]); }
			$drawMainMenu = implode("\n", $desktop);
		}
	?>
	<?php 
		$classes  = $menu['sticker'] ? 'sticker' : '';
		$classes .= ($menu['fullWidth'] == 2) ? ' menufullwidth' : '';
	?>
	<div class="magicmenu clearfix" <?php echo $menu['exclude_html_mobile'] ? 'data-exclude_html_mobile="1"' : '' ?> >
		<ul class="nav-desktop  <?php /* @escapeNotVerified */ echo $classes; ?>"
			data-fullwidth="<?php /* @escapeNotVerified */ echo $menu['fullWidth'] ?>"
			data-breakpoint="<?php /* @escapeNotVerified */ echo $menu['switcher'] ?>"
			>
			<?php echo $drawHomeMenu ?>
			<?php echo $drawMainMenu ?>
			<?php echo $drawExtraMenu ?>
		</ul>
	</div>
<?php endif ?>
<script type="text/javascript">
	require(['jquery','easing','magicmenu']);
</script>
