<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-02-08 22:57:12
 * @@Modify Date: 2020-07-21 14:19:25
 * @@Function:
 */

$menu = $this->_sysCfg->topmenu;

if( !$menu['enabled']){
	echo $this->getChildHtml();
	return;
}
// drawMainMenu vs DrowMobileMenu
$menuHtml = $this->drawMainMenu();
$mobileMenu = $menuHtml['mobile'];
$desktop 	= $menuHtml['desktop'];
$ids  = explode(',', $menu['notIncludeNav']);
foreach ($ids as $id) { unset($desktop[$id]); }
// drawHomeMenu
$drawHomeMenu = $menu['home'] ? $this->drawHomeMenu() : '';
// drawMainMenu
$drawMainMenu = $menu['mainCat'] ? implode("\n", $desktop) : '';
// drawExtMenu ExtraMenu
$drawExtraMenu = $menu['extraCat'] ? $this->drawExtraMenu() : '';
?>
<nav class="navigation mean-nav navigation-mobile" role="navigation" data-action="navigation" <?php echo $menu['exclude_html_desktop'] ? 'data-exclude_html_desktop="1"' : '' ?> >
	<ul class="nav-mobile" data-alo-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
		<?php echo $mobileMenu ?>
		<?php echo $drawExtraMenu ?>
	</ul>
</nav>
<?php 
	$classes  = $menu['sticker'] ? 'sticker' : '';
	$classes .= ($menu['fullWidth'] == 2) ? ' menufullwidth' : '';
?>
<div class="magicmenu clearfix" <?php echo $menu['exclude_html_mobile'] ? 'data-exclude_html_mobile="1"' : '' ?> >
	<ul class="nav-desktop <?php /* @escapeNotVerified */ echo $classes; ?>"			
			data-fullwidth="<?php /* @escapeNotVerified */ echo $menu['fullWidth'] ?>"
			data-breakpoint="<?php /* @escapeNotVerified */ echo $menu['switcher'] ?>"
			>
		<?php echo $drawHomeMenu ?>
		<?php echo $drawMainMenu ?>
		<?php echo $drawExtraMenu ?>
	</ul>
</div>
<script type="text/javascript">
	require(['jquery','easing','magicmenu']);
</script>
