<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-02-08 22:57:12
 * @@Modify Date: 2020-07-21 00:25:34
 * @@Function:
 */

$vmenu = $this->_sysCfg->vmenu;
$menu  = $this->_sysCfg->topmenu;

if(!$vmenu['enabled']) return;
// drawMainMenu vs DrowMobileMenu
$menuHtml = $this->drawMainMenu();
$mobileMenu = $menuHtml['mobile'];
$desktop 	= $menuHtml['desktop'];
$ids  = explode(',', $vmenu['notIncludeNav']);
foreach ($ids as $id) { unset($desktop[$id]); }
// drawHomeMenu
$drawHomeMenu = $vmenu['home'] ? $this->drawHomeMenu() : '';
// drawMainMenu
$drawMainMenu = $vmenu['mainCat'] ? implode("\n", $desktop) : '';
// drawExtMenu ExtraMenu
$drawExtraMenu = $vmenu['extraCat'] ? $this->drawExtraMenu() : '';
?>
<div class="vmagicmenu clearfix" <?php echo $vmenu['exclude_html_mobile'] ? 'data-exclude_html_mobile="1"' : '' ?> >
	<ul class="nav-desktop">
		<?php echo $drawHomeMenu ?>
		<?php echo $drawMainMenu ?>
		<?php echo $drawExtraMenu ?>
	</ul>
</div>
<?php if(!$menu['enabled']) : ?>
<nav class="navigation" role="navigation" <?php echo $menu['exclude_html_desktop'] ? 'data-exclude_html_desktop="1"' : '' ?> >
	<ul class="nav-mobile" data-alo-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
		<?php echo $mobileMenu ?>
		<?php echo $drawExtraMenu ?>
	</ul>
</nav>
<?php endif; ?>
<script type="text/javascript">
	require(['jquery','easing','magicmenu']);
</script>
